import{a as w,S as E,i as d}from"./assets/vendor-CQnpRb22.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&l(i)}).observe(document,{childList:!0,subtree:!0});function n(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(t){if(t.ep)return;t.ep=!0;const o=n(t);fetch(t.href,o)}})();const P="48489244-88d9f9c306d25e531480e36e9",L="https://pixabay.com/api/",S=15;async function p(r,e=1){try{return(await w.get(L,{params:{key:P,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:S,page:e}})).data}catch(n){throw console.error("Помилка запиту:",n),new Error("Не вдалося отримати зображення.")}}const y=document.querySelector(".gallery");let v=new E(".gallery a");function g(r,e=!0){if(e&&(y.innerHTML=""),r.length===0)return;const n=r.map(({webformatURL:l,largeImageURL:t,tags:o,likes:i,views:m,comments:h,downloads:b})=>`
      <a class="gallery__item" href="${t}">
        <div class="photo-card">
          <img src="${l}" alt="${o}" loading="lazy" />
          <div class="info">
            <p><b>Likes:</b> ${i}</p>
            <p><b>Views:</b> ${m}</p>
            <p><b>Comments:</b> ${h}</p>
            <p><b>Downloads:</b> ${b}</p>
          </div>
        </div>
      </a>
    `).join("");y.insertAdjacentHTML("beforeend",n),v.refresh()}function M(){y.innerHTML=""}const R=document.querySelector(".search-form");document.querySelector(".gallery");const u=document.querySelector(".load-more"),s=document.querySelector("#loader");let a=1,c="";const _=15,q=2;function f(r){const e=Math.min(Math.ceil(r/_),q);a>=e?(u.style.display="none",d.info({title:"End of Results",message:"You've reached the end of search results.",position:"topRight"})):u.style.display="block"}R.addEventListener("submit",async r=>{if(r.preventDefault(),c=r.target.elements.searchQuery.value.trim(),!!c){a=1,M(),u.style.display="none",s.style.display="block";try{const e=await p(c,a);if(e.hits.length===0){d.warning({title:"Warning",message:"No images found. Please try a different search.",position:"topRight"}),s.style.display="none";return}g(e.hits),s.style.display="none",f(e.totalHits)}catch(e){console.error("Error fetching images:",e),d.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),s.style.display="none"}}});u.addEventListener("click",async()=>{a+=1,s.style.display="block";try{const r=await p(c,a);g(r.hits,!1);const e=document.querySelector(".gallery a").getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"}),s.style.display="none",f(r.totalHits)}catch(r){console.error("Error loading more images:",r),d.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),s.style.display="none"}});
//# sourceMappingURL=index.js.map
