import{a as y,S as b,i as n}from"./assets/vendor-D3PmPE7A.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&a(s)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const L="48489244-88d9f9c306d25e531480e36e9",v="https://pixabay.com/api/",w=15;async function u(r,o=1){try{return(await y.get(v,{params:{key:L,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:w,page:o}})).data}catch(i){throw console.error("Помилка запиту:",i),new Error("Не вдалося отримати зображення.")}}const d=document.querySelector(".gallery");let E=new b(".gallery a");function f(r,o=!0){if(o&&(d.innerHTML=""),r.length===0)return;const i=r.map(({webformatURL:a,largeImageURL:e,tags:t,likes:s,views:m,comments:g,downloads:h})=>`
      <a class="gallery__item" href="${e}">
        <div class="photo-card">
          <img src="${a}" alt="${t}" loading="lazy" />
          <div class="info">
            <p><b>Likes:</b> ${s}</p>
            <p><b>Views:</b> ${m}</p>
            <p><b>Comments:</b> ${g}</p>
            <p><b>Downloads:</b> ${h}</p>
          </div>
        </div>
      </a>
    `).join("");d.insertAdjacentHTML("beforeend",i),E.refresh()}function S(){d.innerHTML=""}const q=document.querySelector("#search-form");document.querySelector(".gallery");const p=document.querySelector("#load-more");let c="",l=1,P=0;q.addEventListener("submit",async r=>{if(r.preventDefault(),c=r.target.elements.searchQuery.value.trim(),!c){n.warning({title:"Помилка",message:"Поле пошуку не може бути порожнім!",position:"topRight"});return}l=1,S();try{const{hits:o,totalHits:i}=await u(c,l);if(P=i,o.length===0){n.info({title:"Інформація",message:"За вашим запитом нічого не знайдено!",position:"topRight"});return}f(o),p.classList.remove("hidden")}catch{n.error({title:"Помилка",message:"Щось пішло не так. Спробуйте ще раз!",position:"topRight"})}});p.addEventListener("click",async()=>{l+=1;try{const{hits:r}=await u(c,l);if(r.length===0){n.info({title:"Все!",message:"Це були всі результати за вашим запитом!",position:"topRight"}),p.classList.add("hidden");return}f(r)}catch{n.error({title:"Помилка",message:"Не вдалося завантажити додаткові зображення.",position:"topRight"})}});
//# sourceMappingURL=index.js.map
