import{a as m,S as b}from"./assets/vendor-BOc6EdDj.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&l(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const w="48489244-88d9f9c306d25e531480e36e9",E="https://pixabay.com/api/",L=15;async function u(r,t=1){try{return(await m.get(E,{params:{key:w,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:L,page:t}})).data}catch(n){throw console.error("Помилка запиту:",n),new Error("Не вдалося отримати зображення.")}}const y=document.querySelector(".gallery");let S=new b(".gallery a");function p(r,t=!0){if(t&&(y.innerHTML=""),r.length===0)return;const n=r.map(({webformatURL:l,largeImageURL:e,tags:o,likes:a,views:f,comments:g,downloads:h})=>`
      <a class="gallery__item" href="${e}">
        <div class="photo-card">
          <img src="${l}" alt="${o}" loading="lazy" />
          <div class="info">
            <p><b>Likes:</b> ${a}</p>
            <p><b>Views:</b> ${f}</p>
            <p><b>Comments:</b> ${g}</p>
            <p><b>Downloads:</b> ${h}</p>
          </div>
        </div>
      </a>
    `).join("");y.insertAdjacentHTML("beforeend",n),S.refresh()}function v(){y.innerHTML=""}const P=document.querySelector(".search-form");document.querySelector(".gallery");const d=document.querySelector(".load-more"),s=document.querySelector("#loader");let i=1,c="";P.addEventListener("submit",async r=>{if(r.preventDefault(),c=r.target.elements.searchQuery.value.trim(),!!c){i=1,v(),d.style.display="none",s.style.display="block";try{const t=await u(c,i);if(t.hits.length===0){iziToast.warning({title:"Warning",message:"No images found. Please try a different search.",position:"topRight"}),s.style.display="none";return}p(t.hits),s.style.display="none",t.totalHits>i*15&&(d.style.display="block")}catch(t){console.error("Error fetching images:",t),iziToast.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),s.style.display="none"}}});d.addEventListener("click",async()=>{i+=1,s.style.display="block";try{const r=await u(c,i);p(r.hits,!1);const t=document.querySelector(".gallery a").getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"}),(r.hits.length<15||i*15>=r.totalHits)&&(d.style.display="none",iziToast.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),s.style.display="none"}catch(r){console.error("Error loading more images:",r),iziToast.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),s.style.display="none"}});
//# sourceMappingURL=index.js.map
